package com.matt;

import java.io.*;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Scanner;

public class Application {
   
   private static final int DEFAULT_BUCKET_SIZE = 20;
   private static final int DEFAULT_STOP_YEAR = 2050;
   
   //Years chosen by consulting https://en.wikipedia.org/wiki/Demographics_of_the_United_States#/media/File:USA_Population_Pyramid.svg
   //    as well as the charts generated by searchedYearsAcrossAllSystems(), as the data dips around 1955-1960.
   //Idea: The "death curve" really starts aorund age 55-60.  Since we can assume that many people searching on
   //      family HISTORY sites are looking for deceased family members, I decided that search years for those born
   //      less than 45 years ago are probably targeting living people.
   private static final int BIRTH_YEAR_LIVING_CUTOFF = 1965;
   private static final int OTHER_YEAR_LIVING_CUTOFF = 1980;
   
   public static void main(String[] args) {
      
      //DataHandler.searchedYearsAcrossAllSystems("searchYearsAcrossAllSystemsShortBucket.csv", 4, DEFAULT_STOP_YEAR);
      //DataHandler.birthYearSearchesBySystem("birthYearsBySystem.csv", DEFAULT_BUCKET_SIZE, DEFAULT_STOP_YEAR);
      //DataHandler.yearTypesSearchedBySystem("yearTypesBySystem.csv");
      DataHandler.livingPersonsPercentageStats("livingPersonsStatistics.csv",
                                               BIRTH_YEAR_LIVING_CUTOFF, OTHER_YEAR_LIVING_CUTOFF);
      
   }
   
}
